import { PRODUCT_IMAGES } from '../categories';
import { counted, dry, liquid, paste, protein, spice } from './factory';
import type { SeedProductDef } from '../types';

const bunch = [
  { each: 1, label: '1 bunch' },
  { each: 3, label: '3 bunches' },
];
const pcs = [
  { each: 1, label: '1 piece' },
  { each: 5, label: '5 pieces' },
  { each: 10, label: '10 pieces' },
];
const crate = [
  { each: 6, label: 'Half dozen' },
  { each: 12, label: '1 dozen' },
  { each: 30, label: '1 crate' },
];

export const EXPANDED: SeedProductDef[] = [
  dry('cap-rice', 'Cap Rice', 'rice-grains', 'parboiled', 'Thailand', 1480, 'Cap Rice', ['rice', 'parboiled'], 'Popular imported parboiled rice.'),
  dry('mama-gold-rice', 'Mama Gold Rice', 'rice-grains', 'parboiled', 'Thailand', 1520, 'Mama Gold', ['rice', 'parboiled'], 'Mama Gold parboiled rice.'),
  dry('royal-stallion-rice', 'Royal Stallion Rice', 'rice-grains', 'parboiled', 'India', 1580, 'Royal Stallion', ['rice', 'parboiled'], 'Royal Stallion parboiled rice.'),
  dry('tomato-rice', 'Tomato Rice (Party Mix)', 'rice-grains', 'long-grain', 'Lagos, Nigeria', 1500, 'Royal Farms', ['rice', 'jollof'], 'Long grain blended for party jollof.'),
  dry('sticky-rice', 'Sticky Rice', 'rice-grains', 'jasmine', 'Thailand', 2400, 'Golden Gate', ['rice', 'sticky'], 'Glutinous rice for desserts.'),
  dry('wild-rice-blend', 'Wild Rice Blend', 'rice-grains', 'long-grain', 'USA', 4200, 'Harvest Gold', ['rice', 'wild'], 'Imported wild rice blend.', PRODUCT_IMAGES.rice, [1, 2, 5]),
  dry('quinoa', 'Quinoa', 'rice-grains', 'acha', 'Peru', 6500, 'Harvest Gold', ['quinoa'], 'White quinoa grain.', PRODUCT_IMAGES.rice, [1, 2]),
  dry('barley', 'Pearl Barley', 'rice-grains', 'maize', 'Europe', 2800, 'Harvest Gold', ['barley'], 'Pearl barley for soups.', PRODUCT_IMAGES.rice, [1, 2, 5]),
  dry('fonio-white', 'White Fonio', 'rice-grains', 'acha', 'Plateau, Nigeria', 2300, 'Jos Mills', ['fonio', 'acha'], 'Hulled white fonio.'),
  dry('hungry-rice', 'Hungry Rice (Acha Coarse)', 'rice-grains', 'acha', 'Bauchi, Nigeria', 2000, 'Jos Mills', ['acha'], 'Coarse acha for swallows.'),
  dry('maize-grits', 'Maize Grits', 'rice-grains', 'maize', 'Kaduna, Nigeria', 950, 'Northern Harvest', ['maize', 'grits'], 'Coarse maize grits for tuwo.'),
  dry('popcorn-kernels-butter', 'Butter Popcorn Kernels', 'rice-grains', 'maize', 'Plateau, Nigeria', 1100, 'Jos Mills', ['popcorn'], 'Buttery popcorn maize.'),

  dry('oloyin-large', 'Large Oloyin Beans', 'beans-legumes', 'oloyin', 'Oyo, Nigeria', 1650, 'Ibadan Foods', ['beans', 'oloyin'], 'Large-grain honey beans.', PRODUCT_IMAGES.beans),
  dry('potiskum-beans', 'Potiskum White Beans', 'beans-legumes', 'white-beans', 'Yobe, Nigeria', 1280, 'Sahel Grains', ['beans', 'white'], 'Northern white beans.', PRODUCT_IMAGES.beans),
  dry('kidney-beans', 'Red Kidney Beans', 'beans-legumes', 'brown-beans', 'Kano, Nigeria', 1700, 'Sahel Grains', ['kidney-beans'], 'Red kidney beans.', PRODUCT_IMAGES.beans),
  dry('black-beans', 'Black Beans', 'beans-legumes', 'black-eyed', 'Benue, Nigeria', 1900, 'Benue Mills', ['black-beans'], 'Black beans for stews.', PRODUCT_IMAGES.beans, [1, 2, 5, 10]),
  dry('green-peas-dry', 'Dried Green Peas', 'beans-legumes', 'lentils', 'Kano, Nigeria', 1800, 'Sahel Grains', ['peas'], 'Dried green peas.', PRODUCT_IMAGES.beans, [1, 2, 5, 10]),
  dry('chickpeas', 'Chickpeas', 'beans-legumes', 'lentils', 'India', 2400, 'Harvest Gold', ['chickpeas', 'garbanzo'], 'Dried chickpeas.', PRODUCT_IMAGES.beans, [1, 2, 5]),
  dry('mung-beans', 'Mung Beans', 'beans-legumes', 'lentils', 'India', 2600, 'Harvest Gold', ['mung'], 'Green mung beans.', PRODUCT_IMAGES.beans, [1, 2, 5]),
  dry('sesame-seeds', 'Sesame Seeds (Beni)', 'beans-legumes', 'groundnuts', 'Benue, Nigeria', 3200, 'Benue Mills', ['sesame', 'beni'], 'White sesame seeds.', PRODUCT_IMAGES.seed, [1, 2, 5]),
  dry('melon-seeds-egusi-raw', 'Raw Egusi Seeds (Unshelled)', 'soup-thickeners', 'egusi', 'Kogi, Nigeria', 2800, 'Middle Belt Foods', ['egusi'], 'Unshelled melon seeds.', PRODUCT_IMAGES.seed),
  dry('locust-bean-whole', 'Whole Locust Beans', 'beans-legumes', 'ukwa', 'Niger, Nigeria', 3600, 'Northern Harvest', ['iru', 'locust-bean'], 'Dried locust beans before fermenting.', PRODUCT_IMAGES.seed, [1, 2]),

  dry('garri-ijebu-yellow', 'Yellow Ijebu Garri', 'swallows-flours', 'garri', 'Ogun, Nigeria', 1150, 'Ijebu Mills', ['garri', 'ijebu', 'yellow'], 'Yellow Ijebu-style garri.', PRODUCT_IMAGES.flour),
  dry('garri-soaking', 'Soaking Garri (Coarse)', 'swallows-flours', 'garri', 'Oyo, Nigeria', 850, 'Ibadan Foods', ['garri', 'soaking'], 'Coarse garri for soaking.', PRODUCT_IMAGES.flour),
  dry('fufu-fresh-mix', 'Wet Fufu Mix (Dried)', 'swallows-flours', 'fufu', 'Imo, Nigeria', 1500, 'Eastern Harvest', ['fufu'], 'Dried fermented fufu that reconstitutes wet.', PRODUCT_IMAGES.flour),
  dry('semo-golden-penny', 'Golden Penny Semo', 'swallows-flours', 'semo', 'Lagos, Nigeria', 1650, 'Golden Penny', ['semo'], 'Golden Penny semolina swallow.', PRODUCT_IMAGES.flour, [1, 2, 5, 10]),
  dry('poundo-ayoola', 'Ayoola Poundo Yam', 'swallows-flours', 'poundo', 'Oyo, Nigeria', 2500, 'Ayoola', ['poundo'], 'Ayoola brand poundo yam.', PRODUCT_IMAGES.flour, [1, 2, 5]),
  dry('amala-lafun', 'Lafun (Cassava Amala)', 'swallows-flours', 'elubo', 'Oyo, Nigeria', 1300, 'Ibadan Foods', ['lafun', 'amala'], 'White cassava flour for lafun.', PRODUCT_IMAGES.flour),
  dry('wheat-swallow', 'Wheat Swallow Mix', 'swallows-flours', 'semo', 'Lagos, Nigeria', 1700, 'Honeywell', ['wheat', 'swallow'], 'Whole-wheat swallow mix.', PRODUCT_IMAGES.flour, [1, 2, 5]),
  dry('oat-swallow', 'Oat Swallow Mix', 'swallows-flours', 'ogi', 'Lagos, Nigeria', 2200, 'Quaker', ['oat', 'swallow'], 'Oat-based swallow blend.', PRODUCT_IMAGES.flour, [1, 2, 5]),
  dry('plantain-fufu', 'Plantain Fufu Mix', 'swallows-flours', 'plantain-flour', 'Ondo, Nigeria', 2100, 'Sunshine Foods', ['plantain', 'fufu'], 'Unripe plantain fufu mix.', PRODUCT_IMAGES.flour, [1, 2, 5]),
  dry('cocoyam-flour', 'Cocoyam Flour', 'swallows-flours', 'elubo', 'Imo, Nigeria', 1900, 'Eastern Harvest', ['cocoyam', 'flour'], 'Dried cocoyam flour.', PRODUCT_IMAGES.flour, [1, 2, 5]),
  dry('oats-rolled', 'Rolled Oats', 'breakfast-bakery', 'oats', 'Lagos, Nigeria', 2400, 'Quaker', ['oats'], 'Rolled breakfast oats.', PRODUCT_IMAGES.breakfast, [1, 2, 5]),
  dry('oats-instant', 'Instant Oats', 'breakfast-bakery', 'oats', 'Lagos, Nigeria', 2600, 'Quaker', ['oats', 'instant'], 'Instant oat sachets by weight.', PRODUCT_IMAGES.breakfast, [1, 2]),
  dry('golden-morn', 'Golden Morn', 'breakfast-bakery', 'cereal', 'Lagos, Nigeria', 3200, 'Nestle', ['golden-morn', 'cereal'], 'Maize-soy breakfast cereal.', PRODUCT_IMAGES.breakfast, [1, 2, 5]),
  dry('cornflakes', 'Cornflakes', 'breakfast-bakery', 'cereal', 'Lagos, Nigeria', 2800, 'Nasco', ['cornflakes'], 'Toasted cornflakes.', PRODUCT_IMAGES.breakfast, [1, 2]),
  dry('granola', 'Granola', 'breakfast-bakery', 'cereal', 'Lagos, Nigeria', 4500, 'Tropical Sun', ['granola'], 'Honey granola clusters.', PRODUCT_IMAGES.breakfast, [1, 2]),

  liquid('devon-kings-oil', 'Devon Kings Oil', 'oils-fats', 'vegetable-oil', 'Lagos, Nigeria', 1600, 'Devon Kings', ['vegetable-oil'], 'Devon Kings vegetable oil.', [0.75, 1, 2, 5, 25]),
  liquid('gino-oil', 'Gino Vegetable Oil', 'oils-fats', 'vegetable-oil', 'Lagos, Nigeria', 1550, 'Gino', ['vegetable-oil'], 'Gino cooking oil.', [1, 2, 5]),
  liquid('turkey-brand-oil', 'Turkey Brand Oil', 'oils-fats', 'vegetable-oil', 'Lagos, Nigeria', 1700, 'Turkey Brand', ['vegetable-oil'], 'Turkey Brand vegetable oil.', [1, 2, 5, 25]),
  liquid('palm-oil-delta', 'Delta Red Palm Oil', 'oils-fats', 'palm-oil', 'Delta, Nigeria', 1800, 'Delta Foods', ['palm-oil'], 'Unrefined red palm oil.', [1, 2, 5, 25]),
  liquid('palm-oil-ondo', 'Ondo Palm Oil', 'oils-fats', 'palm-oil', 'Ondo, Nigeria', 1850, 'Sunshine Foods', ['palm-oil'], 'Eastern-style red oil.', [1, 2, 5]),
  liquid('bleached-palm-oil', 'Bleached Palm Oil', 'oils-fats', 'palm-oil', 'Lagos, Nigeria', 1500, 'Kings', ['palm-oil', 'bleached'], 'Light palm olein.', [1, 2, 5, 25]),
  liquid('groundnut-oil-cold', 'Cold-pressed Groundnut Oil', 'oils-fats', 'groundnut-oil', 'Kano, Nigeria', 2800, 'Sahel Grains', ['groundnut-oil'], 'Artisan groundnut oil.', [0.5, 1, 2]),
  liquid('coconut-oil-virgin', 'Virgin Coconut Oil', 'oils-fats', 'coconut-oil', 'Lagos, Nigeria', 4200, 'Tropical Sun', ['coconut-oil'], 'Virgin coconut oil.', [0.5, 1]),
  liquid('olive-oil', 'Olive Oil', 'oils-fats', 'vegetable-oil', 'Spain', 6500, 'Bertolli', ['olive-oil'], 'Imported olive oil.', [0.5, 1]),
  dry('butter-blue-band-block', 'Blue Band Brick', 'oils-fats', 'margarine', 'Lagos, Nigeria', 3400, 'Blue Band', ['margarine'], 'Blue Band baking margarine.', PRODUCT_IMAGES.oil, [1, 2]),

  dry('egusi-shelled', 'Shelled Egusi', 'soup-thickeners', 'egusi', 'Kogi, Nigeria', 3800, 'Middle Belt Foods', ['egusi'], 'Clean shelled melon seeds.', PRODUCT_IMAGES.seed),
  dry('egusi-ground', 'Ground Egusi', 'soup-thickeners', 'egusi', 'Kogi, Nigeria', 4200, 'Middle Belt Foods', ['egusi', 'ground'], 'Ready-milled egusi.', PRODUCT_IMAGES.seed, [1, 2, 5]),
  dry('ogbono-whole', 'Whole Ogbono Seeds', 'soup-thickeners', 'ogbono', 'Cross River, Nigeria', 5200, 'Niger Delta Foods', ['ogbono'], 'Whole ogbono seeds.', PRODUCT_IMAGES.seed, [1, 2, 5]),
  dry('ogbono-ground', 'Ground Ogbono', 'soup-thickeners', 'ogbono', 'Cross River, Nigeria', 5600, 'Niger Delta Foods', ['ogbono', 'ground'], 'Milled ogbono for draw soup.', PRODUCT_IMAGES.seed, [1, 2, 5]),
  dry('achi-seeds', 'Achi Seeds', 'soup-thickeners', 'achi', 'Enugu, Nigeria', 4800, 'Eastern Harvest', ['achi'], 'Achi soup thickener seeds.', PRODUCT_IMAGES.seed, [1, 2]),
  dry('ofor-seeds', 'Ofor Seeds', 'soup-thickeners', 'ofor', 'Anambra, Nigeria', 5000, 'Eastern Harvest', ['ofor'], 'Ofor thickener.', PRODUCT_IMAGES.seed, [1, 2]),
  dry('uziza-seed-dry', 'Dried Uziza Seeds', 'soup-thickeners', 'uziza-seed', 'Rivers, Nigeria', 7000, 'Niger Delta Foods', ['uziza', 'seed'], 'Peppery uziza seeds.', PRODUCT_IMAGES.spice, [1]),
  dry('egusi-itoo', 'Itoo Melon Seeds', 'soup-thickeners', 'melon', 'Oyo, Nigeria', 3400, 'Ibadan Foods', ['itoo', 'melon'], 'Itoo melon for local soups.', PRODUCT_IMAGES.seed, [1, 2, 5]),

  spice('curry-powder-duke', 'Duke Curry Powder', 'curry-thyme', 'Lagos, Nigeria', 7200, 'Duke', ['curry'], 'Duke brand curry powder.'),
  spice('thyme-leaves', 'Dried Thyme', 'curry-thyme', 'Morocco', 6800, 'Tropical Sun', ['thyme'], 'Dried thyme leaves.'),
  spice('ginger-powder', 'Ginger Powder', 'ginger-garlic', 'Kaduna, Nigeria', 5400, 'Sahel Spices', ['ginger'], 'Ground dry ginger.'),
  spice('garlic-powder', 'Garlic Powder', 'ginger-garlic', 'Kano, Nigeria', 5600, 'Sahel Spices', ['garlic'], 'Ground garlic.'),
  spice('onion-powder', 'Onion Powder', 'ginger-garlic', 'Kano, Nigeria', 5000, 'Sahel Spices', ['onion-powder'], 'Dehydrated onion powder.'),
  spice('cameroon-pepper', 'Cameroon Pepper', 'pepper-dry', 'Cameroon', 9000, 'Niger Delta Foods', ['pepper', 'cameroon'], 'Hot Cameroon pepper.'),
  spice('ata-iroko', 'Ata Iroko (Dry Chilli)', 'pepper-dry', 'Kano, Nigeria', 6200, 'Sahel Spices', ['chilli', 'pepper'], 'Dried red chilli peppers.'),
  spice('ehuru', 'Ehuru (Calabash Nutmeg)', 'local-spices', 'Anambra, Nigeria', 11000, 'Eastern Harvest', ['ehuru'], 'African nutmeg seeds.'),
  spice('uda', 'Uda (Grains of Selim)', 'local-spices', 'Cross River, Nigeria', 10500, 'Niger Delta Foods', ['uda'], 'Uda pods for pepper soup.'),
  spice('uziza-pepper', 'Uziza Pepper', 'local-spices', 'Rivers, Nigeria', 9800, 'Niger Delta Foods', ['uziza'], 'Dried uziza peppercorns.'),
  spice('crayfish-ground', 'Ground Crayfish', 'crayfish', 'Akwa Ibom, Nigeria', 8500, 'Niger Delta Foods', ['crayfish'], 'Fine ground crayfish.'),
  spice('crayfish-whole-dry', 'Whole Dried Crayfish', 'crayfish', 'Akwa Ibom, Nigeria', 7800, 'Niger Delta Foods', ['crayfish'], 'Whole dried crayfish.'),
  spice('salt-iodized', 'Iodized Table Salt', 'salt', 'Lagos, Nigeria', 400, 'Dangote', ['salt'], 'Iodized table salt.', [250, 500, 1000]),
  spice('salt-sea', 'Sea Salt', 'salt', 'Lagos, Nigeria', 900, 'Tropical Sun', ['salt', 'sea'], 'Coarse sea salt.', [250, 500]),
  spice('seasoning-mix-all-purpose', 'All-Purpose Seasoning', 'curry-thyme', 'Lagos, Nigeria', 6400, 'Knorr', ['seasoning'], 'All-purpose dry seasoning.'),
  spice('turmeric', 'Turmeric Powder', 'curry-thyme', 'India', 4800, 'Tropical Sun', ['turmeric'], 'Ground turmeric.'),
  spice('cinnamon', 'Cinnamon Sticks', 'local-spices', 'Sri Lanka', 12000, 'Tropical Sun', ['cinnamon'], 'Cinnamon quills.'),
  spice('star-anise', 'Star Anise', 'local-spices', 'China', 13000, 'Tropical Sun', ['star-anise'], 'Whole star anise.'),

  paste('gino-paste', 'Gino Tomato Paste', 'tomato-paste', 'Lagos, Nigeria', 2800, 'Gino', ['tomato', 'paste'], 'Gino tomato paste tins.'),
  paste('sonia-paste', 'Sonia Tomato Paste', 'tomato-paste', 'Lagos, Nigeria', 2600, 'Sonia', ['tomato', 'paste'], 'Sonia tomato paste.'),
  paste('tasty-tom-paste', 'Tasty Tom Paste', 'tomato-paste', 'Lagos, Nigeria', 2700, 'Tasty Tom', ['tomato', 'paste'], 'Tasty Tom concentrated paste.'),
  paste('pepper-mix-ata-din-din', 'Ata Din Din Mix', 'pepper-mix', 'Lagos, Nigeria', 2200, 'City Foods', ['pepper-mix'], 'Blended stew pepper mix.'),
  paste('scotch-bonnet-puree', 'Ata Rodo Puree', 'pepper-mix', 'Kaduna, Nigeria', 2400, 'Sahel Produce', ['ata-rodo'], 'Blended scotch bonnet puree.'),
  paste('iru-paste', 'Iru Paste', 'iru-ogiri', 'Oyo, Nigeria', 3600, 'Ibadan Foods', ['iru'], 'Soft fermented locust bean paste.'),
  paste('ogiri-okpei', 'Ogiri Okpei', 'iru-ogiri', 'Anambra, Nigeria', 4000, 'Eastern Harvest', ['ogiri'], 'Castor-seed ogiri balls.'),
  paste('ogiri-isi', 'Ogiri Isi', 'iru-ogiri', 'Imo, Nigeria', 4200, 'Eastern Harvest', ['ogiri'], 'Strong ogiri isi condiment.'),
  liquid('vinegar-white', 'White Vinegar', 'condiments-pastes', 'sauces', 'Lagos, Nigeria', 900, 'Heinz', ['vinegar'], 'White distilled vinegar.', [0.5, 1], PRODUCT_IMAGES.canned),
  liquid('vinegar-apple', 'Apple Cider Vinegar', 'condiments-pastes', 'sauces', 'Lagos, Nigeria', 1800, 'Heinz', ['vinegar'], 'Apple cider vinegar.', [0.5, 1], PRODUCT_IMAGES.canned),
  liquid('soy-sauce', 'Soy Sauce', 'condiments-pastes', 'sauces', 'Lagos, Nigeria', 2200, 'Tropical Sun', ['soy-sauce'], 'Light soy sauce.', [0.25, 0.5, 1], PRODUCT_IMAGES.canned),
  liquid('worcestershire', 'Worcestershire Sauce', 'condiments-pastes', 'sauces', 'UK', 4800, 'Lea & Perrins', ['worcestershire'], 'Worcestershire sauce.', [0.15, 0.29], PRODUCT_IMAGES.canned),
  paste('mayonnaise', 'Mayonnaise', 'sauces', 'Lagos, Nigeria', 3200, 'Heinz', ['mayo'], 'Creamy mayonnaise.', [250, 400, 800]),
  paste('ketchup', 'Tomato Ketchup', 'sauces', 'Lagos, Nigeria', 2400, 'Heinz', ['ketchup'], 'Tomato ketchup.', [250, 400, 800]),
  paste('chili-sauce', 'Chilli Sauce', 'sauces', 'Lagos, Nigeria', 2600, 'Mama Africa', ['chilli', 'sauce'], 'Hot chilli table sauce.'),

  counted('tatase', 'Tatase (Sweet Pepper)', 'fresh-produce', 'pepper-fresh', 'Kano, Nigeria', 120, 'Jos Farms', ['tatase', 'pepper'], 'Red tatase peppers.', pcs),
  counted('shombo', 'Shombo (Long Pepper)', 'fresh-produce', 'pepper-fresh', 'Kaduna, Nigeria', 80, 'Sahel Produce', ['shombo'], 'Long cayenne peppers.', [
    { each: 10, label: '10 pcs' },
    { each: 25, label: '25 pcs' },
  ]),
  counted('ata-rodo', 'Ata Rodo', 'fresh-produce', 'pepper-fresh', 'Kaduna, Nigeria', 30, 'Sahel Produce', ['ata-rodo'], 'Fresh scotch bonnets.', [
    { each: 20, label: '20 pcs' },
    { each: 50, label: '50 pcs' },
  ]),
  counted('onion-red', 'Red Onions', 'fresh-produce', 'onion', 'Kano, Nigeria', 150, 'Sahel Produce', ['onion'], 'Red cooking onions.', [
    { each: 5, label: '5 bulbs' },
    { each: 10, label: '10 bulbs' },
    { each: 25, label: 'Paint bucket' },
  ]),
  counted('onion-white', 'White Onions', 'fresh-produce', 'onion', 'Kano, Nigeria', 160, 'Sahel Produce', ['onion', 'white'], 'White onions.', [
    { each: 5, label: '5 bulbs' },
    { each: 10, label: '10 bulbs' },
  ]),
  counted('ugu', 'Ugu Leaves', 'fresh-produce', 'leafy', 'Jos, Nigeria', 400, 'Jos Farms', ['ugu', 'pumpkin-leaf'], 'Fresh ugu bunches.', bunch),
  counted('waterleaf', 'Waterleaf', 'fresh-produce', 'leafy', 'Lagos, Nigeria', 250, 'City Foods', ['waterleaf'], 'Fresh waterleaf.', bunch),
  counted('bitterleaf', 'Bitterleaf', 'fresh-produce', 'leafy', 'Anambra, Nigeria', 350, 'Eastern Harvest', ['bitterleaf'], 'Washed bitterleaf.', bunch),
  counted('scent-leaf', 'Scent Leaf (Nchuanwu)', 'fresh-produce', 'leafy', 'Enugu, Nigeria', 200, 'Eastern Harvest', ['scent-leaf'], 'Scent leaf bunches.', bunch),
  counted('okra-fresh', 'Fresh Okra', 'fresh-produce', 'okra', 'Kano, Nigeria', 40, 'Sahel Produce', ['okra'], 'Fresh okra pods.', [
    { each: 10, label: '10 pods' },
    { each: 25, label: '25 pods' },
  ]),
  counted('garden-egg-white', 'White Garden Eggs', 'fresh-produce', 'garden-egg', 'Jos, Nigeria', 50, 'Jos Farms', ['garden-egg'], 'White garden eggs.', [
    { each: 10, label: '10 pcs' },
    { each: 25, label: '25 pcs' },
  ]),
  counted('garden-egg-green', 'Green Garden Eggs', 'fresh-produce', 'garden-egg', 'Jos, Nigeria', 45, 'Jos Farms', ['garden-egg'], 'Green garden eggs.', [
    { each: 10, label: '10 pcs' },
    { each: 25, label: '25 pcs' },
  ]),
  counted('pumpkin-leaves-dried', 'Dried Ugu', 'fresh-produce', 'leafy', 'Jos, Nigeria', 80, 'Jos Farms', ['ugu', 'dried'], 'Sun-dried ugu packs.', [
    { each: 1, label: '1 pack' },
    { each: 3, label: '3 packs' },
  ]),

  counted('yam-white', 'White Yam', 'tubers-roots', 'yam', 'Benue, Nigeria', 2500, 'Benue Mills', ['yam'], 'White yam tubers.', pcs, PRODUCT_IMAGES.tuber),
  counted('yam-puna', 'Puna Yam', 'tubers-roots', 'yam', 'Oyo, Nigeria', 2800, 'Ibadan Foods', ['yam', 'puna'], 'Puna yam for pounding.', pcs, PRODUCT_IMAGES.tuber),
  counted('sweet-potato-orange', 'Orange Sweet Potato', 'tubers-roots', 'sweet-potato', 'Plateau, Nigeria', 400, 'Jos Farms', ['sweet-potato'], 'Orange-flesh sweet potatoes.', pcs, PRODUCT_IMAGES.tuber),
  counted('irish-potato', 'Irish Potatoes', 'tubers-roots', 'irish-potato', 'Plateau, Nigeria', 80, 'Jos Farms', ['potato'], 'Irish potatoes.', [
    { each: 10, label: '10 pcs' },
    { each: 25, label: 'Paint bucket' },
  ], PRODUCT_IMAGES.tuber),
  counted('cassava-fresh', 'Fresh Cassava', 'tubers-roots', 'cassava', 'Ogun, Nigeria', 600, 'Ijebu Mills', ['cassava'], 'Fresh cassava roots.', pcs, PRODUCT_IMAGES.tuber),
  counted('cocoyam-fresh', 'Cocoyam', 'tubers-roots', 'cocoyam', 'Imo, Nigeria', 500, 'Eastern Harvest', ['cocoyam'], 'Fresh cocoyam corms.', pcs, PRODUCT_IMAGES.tuber),
  counted('unripe-plantain', 'Unripe Plantain', 'plantain-banana', 'unripe-plantain', 'Ondo, Nigeria', 250, 'Sunshine Foods', ['plantain', 'unripe'], 'Green plantains.', [
    { each: 5, label: '5 fingers' },
    { each: 12, label: '1 bunch' },
  ], PRODUCT_IMAGES.plantain),
  counted('ripe-plantain', 'Ripe Plantain', 'plantain-banana', 'ripe-plantain', 'Ondo, Nigeria', 280, 'Sunshine Foods', ['plantain', 'ripe'], 'Ripe plantains.', [
    { each: 5, label: '5 fingers' },
    { each: 12, label: '1 bunch' },
  ], PRODUCT_IMAGES.plantain),
  counted('banana-cavendish', 'Cavendish Banana', 'plantain-banana', 'banana', 'Plateau, Nigeria', 80, 'Jos Farms', ['banana'], 'Sweet bananas.', [
    { each: 6, label: '6 fingers' },
    { each: 12, label: '1 dozen' },
  ], PRODUCT_IMAGES.plantain),

  protein('beef-stewing', 'Stewing Beef', 'meat-offals', 'beef', 'Kaduna, Nigeria', 4200, 'Northern Meats', ['beef'], 'Cubed stewing beef.'),
  protein('beef-mince', 'Minced Beef', 'meat-offals', 'beef', 'Lagos, Nigeria', 4500, 'City Meats', ['beef', 'mince'], 'Lean minced beef.'),
  protein('goat-meat', 'Goat Meat', 'meat-offals', 'goat', 'Sokoto, Nigeria', 5200, 'Sahel Meats', ['goat'], 'Cut goat meat.'),
  protein('chicken-whole-parts', 'Chicken Parts', 'meat-offals', 'chicken', 'Ogun, Nigeria', 3200, 'CHI Farms', ['chicken'], 'Mixed chicken parts.'),
  protein('turkey-parts', 'Turkey Parts', 'meat-offals', 'turkey', 'Ogun, Nigeria', 3800, 'CHI Farms', ['turkey'], 'Mixed turkey parts.'),
  protein('ponmo-wet', 'Wet Ponmo', 'meat-offals', 'ponmo', 'Oyo, Nigeria', 1800, 'Ibadan Foods', ['ponmo'], 'Soft wet cow skin.'),
  protein('shaki', 'Shaki (Tripe)', 'meat-offals', 'offals', 'Kaduna, Nigeria', 2800, 'Northern Meats', ['shaki', 'tripe'], 'Cleaned tripe.'),
  protein('roundabout', 'Roundabout', 'meat-offals', 'offals', 'Kaduna, Nigeria', 2600, 'Northern Meats', ['roundabout'], 'Intestine offals.'),
  protein('liver-beef', 'Beef Liver', 'meat-offals', 'offals', 'Kaduna, Nigeria', 3000, 'Northern Meats', ['liver'], 'Fresh beef liver.'),
  protein('kidney-beef', 'Beef Kidney', 'meat-offals', 'offals', 'Kaduna, Nigeria', 2400, 'Northern Meats', ['kidney'], 'Beef kidney.'),

  protein('tilapia-fresh', 'Fresh Tilapia', 'fish-seafood', 'fresh-fish', 'Lagos, Nigeria', 2800, 'Lagos Fish Market', ['tilapia'], 'Fresh tilapia.', [1, 2, 5], PRODUCT_IMAGES.fish),
  protein('catfish-fresh', 'Fresh Catfish', 'fish-seafood', 'fresh-fish', 'Delta, Nigeria', 3200, 'Delta Foods', ['catfish'], 'Live-killed catfish.', [1, 2, 5], PRODUCT_IMAGES.fish),
  protein('croaker', 'Croaker', 'fish-seafood', 'fresh-fish', 'Lagos, Nigeria', 3600, 'Lagos Fish Market', ['croaker'], 'Fresh croaker.', [1, 2], PRODUCT_IMAGES.fish),
  protein('stockfish-body', 'Stockfish Body', 'fish-seafood', 'stockfish', 'Norway', 7800, 'Frozen Seas', ['stockfish'], 'Stockfish body pieces.', [1, 2], PRODUCT_IMAGES.fish),
  protein('okporoko', 'Okporoko (Stockfish)', 'fish-seafood', 'stockfish', 'Norway', 8200, 'Frozen Seas', ['okporoko', 'stockfish'], 'Hard-dried stockfish.', [1, 2], PRODUCT_IMAGES.fish),
  protein('dried-catfish', 'Dried Catfish', 'fish-seafood', 'dried-fish', 'Kebbi, Nigeria', 5400, 'Kebbi Rice', ['catfish', 'dried'], 'Sun-dried catfish.', [1, 2], PRODUCT_IMAGES.fish),
  protein('shrimp-fresh', 'Fresh Shrimp', 'fish-seafood', 'shrimp', 'Akwa Ibom, Nigeria', 6500, 'Niger Delta Foods', ['shrimp'], 'Fresh shrimp.', [1, 2], PRODUCT_IMAGES.fish),
  protein('snail-fresh', 'Fresh Snail', 'fish-seafood', 'snail', 'Ogun, Nigeria', 4800, 'Ijebu Mills', ['snail'], 'Cleaned giant snails.', [1, 2], PRODUCT_IMAGES.fish),
  protein('periwinkle', 'Periwinkle', 'fish-seafood', 'snail', 'Rivers, Nigeria', 3600, 'Niger Delta Foods', ['periwinkle'], 'Shelled periwinkle.', [1, 2], PRODUCT_IMAGES.fish),

  counted('quail-eggs', 'Quail Eggs', 'eggs-dairy', 'eggs', 'Ogun, Nigeria', 40, 'CHI Farms', ['eggs', 'quail'], 'Fresh quail eggs.', crate, PRODUCT_IMAGES.dairy),
  liquid('eva-water', 'Eva Table Water', 'drinks', 'water', 'Lagos, Nigeria', 250, 'Eva', ['water'], 'Eva bottled water.', [0.75, 1.5], PRODUCT_IMAGES.drink),
  liquid('ragolis-water', 'Ragolis Water', 'drinks', 'water', 'Lagos, Nigeria', 240, 'Ragolis', ['water'], 'Ragolis table water.', [0.75, 1.5], PRODUCT_IMAGES.drink),
  liquid('maltina', 'Maltina', 'drinks', 'malt-soda', 'Lagos, Nigeria', 900, 'Maltina', ['malt'], 'Maltina non-alcoholic malt.', [0.33, 1], PRODUCT_IMAGES.drink),
  liquid('malta-guinness', 'Malta Guinness', 'drinks', 'malt-soda', 'Lagos, Nigeria', 950, 'Guinness', ['malt'], 'Malta Guinness.', [0.33, 1], PRODUCT_IMAGES.drink),
  liquid('coke', 'Coca-Cola', 'drinks', 'malt-soda', 'Lagos, Nigeria', 700, 'Coca-Cola', ['soda', 'coke'], 'Coca-Cola.', [0.35, 0.5, 1.5], PRODUCT_IMAGES.drink),
  liquid('chivita-pineapple', 'Chivita Pineapple', 'drinks', 'juice', 'Lagos, Nigeria', 1400, 'Chivita', ['juice', 'pineapple'], 'Pineapple juice.', [1], PRODUCT_IMAGES.drink),
  liquid('chivita-orange', 'Chivita Orange', 'drinks', 'juice', 'Lagos, Nigeria', 1400, 'Chivita', ['juice', 'orange'], 'Orange juice.', [1], PRODUCT_IMAGES.drink),
  dry('nescafe', 'Nescafe Classic', 'drinks', 'tea-coffee', 'Lagos, Nigeria', 12000, 'Nescafe', ['coffee'], 'Instant coffee.', PRODUCT_IMAGES.drink, [1]),
  dry('milo', 'Milo', 'drinks', 'tea-coffee', 'Lagos, Nigeria', 6200, 'Nestle', ['milo', 'cocoa'], 'Milo chocolate malt.', PRODUCT_IMAGES.drink, [1, 2, 5]),
  dry('bournvita', 'Bournvita', 'drinks', 'tea-coffee', 'Lagos, Nigeria', 6100, 'Cadbury', ['bournvita'], 'Bournvita tin refill equivalent.', PRODUCT_IMAGES.drink, [1, 2]),
  dry('lipton-tea', 'Lipton Yellow Label', 'drinks', 'tea-coffee', 'Lagos, Nigeria', 9000, 'Lipton', ['tea'], 'Lipton tea by weight.', PRODUCT_IMAGES.drink, [1]),

  dry('geisha-sardine-alt', 'Titus Sardines', 'canned-bottled', 'canned-fish', 'Morocco', 4200, 'Titus', ['sardine', 'canned'], 'Titus sardines in oil.', PRODUCT_IMAGES.canned, [1]),
  {
    slug: 'geisha-sardine',
    name: 'Geisha Sardines',
    categorySlug: 'canned-bottled',
    subcategorySlug: 'canned-fish',
    familySlug: 'protein-mass',
    origin: 'China',
    description: 'Geisha sardines in tomato sauce.',
    tags: ['geisha', 'sardine'],
    imageUrl: PRODUCT_IMAGES.canned,
    packs: [
      { brand: 'Geisha', unitSlug: 'gram', packAmount: 155, packageLabel: '155g', priceKobo: 90000, retailPriceKobo: 110000 },
      { brand: 'Geisha', unitSlug: 'gram', packAmount: 425, packageLabel: '425g', priceKobo: 210000, retailPriceKobo: 250000 },
    ],
  },
  {
    slug: 'exeter-corned-beef',
    name: 'Exeter Corned Beef',
    categorySlug: 'canned-bottled',
    subcategorySlug: 'corned-beef',
    familySlug: 'protein-mass',
    origin: 'Brazil',
    description: 'Exeter corned beef.',
    tags: ['corned-beef'],
    imageUrl: PRODUCT_IMAGES.canned,
    packs: [
      { brand: 'Exeter', unitSlug: 'gram', packAmount: 340, packageLabel: '340g', priceKobo: 280000, retailPriceKobo: 330000 },
    ],
  },
  {
    slug: 'heinz-baked-beans',
    name: 'Heinz Baked Beans',
    categorySlug: 'canned-bottled',
    subcategorySlug: 'baked-beans',
    familySlug: 'dry-staple',
    origin: 'UK',
    description: 'Heinz baked beans in tomato sauce.',
    tags: ['baked-beans'],
    imageUrl: PRODUCT_IMAGES.canned,
    packs: [
      { brand: 'Heinz', unitSlug: 'gram', packAmount: 415, packageLabel: '415g', priceKobo: 180000, retailPriceKobo: 220000 },
    ],
  },
  {
    slug: 'canned-tomato-roma',
    name: 'Canned Roma Tomatoes',
    categorySlug: 'canned-bottled',
    subcategorySlug: 'canned-tomato',
    familySlug: 'paste',
    origin: 'Italy',
    description: 'Peeled roma tomatoes in juice.',
    tags: ['canned-tomato'],
    imageUrl: PRODUCT_IMAGES.canned,
    packs: [
      { brand: 'Gino', unitSlug: 'gram', packAmount: 400, packageLabel: '400g', priceKobo: 95000, retailPriceKobo: 120000 },
      { brand: 'Gino', unitSlug: 'gram', packAmount: 800, packageLabel: '800g', priceKobo: 170000, retailPriceKobo: 210000 },
    ],
  },

  protein('frozen-croaker', 'Frozen Croaker', 'frozen', 'frozen-fish', 'Lagos, Nigeria', 3400, 'Frozen Seas', ['frozen', 'croaker'], 'IQF croaker.', [1, 2, 5], PRODUCT_IMAGES.frozen),
  protein('frozen-shrimp', 'Frozen Shrimp', 'frozen', 'frozen-protein', 'Akwa Ibom, Nigeria', 7200, 'Frozen Seas', ['frozen', 'shrimp'], 'Frozen peeled shrimp.', [1, 2], PRODUCT_IMAGES.frozen),
  protein('frozen-chicken', 'Frozen Whole Chicken', 'frozen', 'frozen-protein', 'Ogun, Nigeria', 2800, 'CHI Farms', ['frozen', 'chicken'], 'Frozen whole chicken.', [1, 2], PRODUCT_IMAGES.frozen),
  dry('frozen-spinach', 'Frozen Spinach', 'frozen', 'frozen-veg', 'Lagos, Nigeria', 1800, 'Tropical Sun', ['frozen', 'spinach'], 'Frozen chopped spinach.', PRODUCT_IMAGES.frozen, [1, 2]),
  dry('frozen-mixed-veg', 'Frozen Mixed Vegetables', 'frozen', 'frozen-veg', 'Lagos, Nigeria', 2000, 'Tropical Sun', ['frozen', 'vegetables'], 'Peas, carrots and corn mix.', PRODUCT_IMAGES.frozen, [1, 2]),

  counted('agege-bread', 'Agege Bread', 'breakfast-bakery', 'bread', 'Lagos, Nigeria', 800, 'Local Bakery', ['bread', 'agege'], 'Soft Agege loaves.', [
    { each: 1, label: '1 loaf' },
    { each: 3, label: '3 loaves' },
  ], PRODUCT_IMAGES.breakfast),
  counted('sliced-bread', 'Sliced Bread', 'breakfast-bakery', 'bread', 'Lagos, Nigeria', 1200, 'UAC', ['bread'], 'Sliced white bread.', [
    { each: 1, label: '1 loaf' },
    { each: 2, label: '2 loaves' },
  ], PRODUCT_IMAGES.breakfast),

  dry('caster-sugar', 'Caster Sugar', 'baking-staples', 'sugar', 'Lagos, Nigeria', 1700, 'Dangote', ['sugar', 'caster'], 'Fine caster sugar.', PRODUCT_IMAGES.baking, [1, 2]),
  dry('honeywell-flour', 'Honeywell Wheat Flour', 'baking-staples', 'flour-wheat', 'Lagos, Nigeria', 1150, 'Honeywell', ['flour'], 'Honeywell wheat flour.', PRODUCT_IMAGES.flour, [1, 2, 5, 10, 25]),
  dry('dangote-flour', 'Dangote Wheat Flour', 'baking-staples', 'flour-wheat', 'Lagos, Nigeria', 1120, 'Dangote', ['flour'], 'Dangote wheat flour.', PRODUCT_IMAGES.flour, [1, 2, 5, 10]),
  dry('yeast-fresh-dry', 'Active Dry Yeast', 'baking-staples', 'yeast', 'Lagos, Nigeria', 7500, 'Angel', ['yeast'], 'Active dry yeast.', PRODUCT_IMAGES.baking, [1]),
  dry('vanilla-sugar', 'Vanilla Sugar', 'baking-staples', 'baking-aids', 'Lagos, Nigeria', 4000, 'Royal', ['vanilla'], 'Vanilla sugar sachets by weight.', PRODUCT_IMAGES.baking, [1]),
  dry('cocoa-powder', 'Cocoa Powder', 'baking-staples', 'baking-aids', 'Lagos, Nigeria', 5500, 'Cadbury', ['cocoa'], 'Unsweetened cocoa powder.', PRODUCT_IMAGES.baking, [1, 2]),

  dry('caprice-gold', 'Caprice Gold Rice', 'rice-grains', 'parboiled', 'Thailand', 1510, 'Caprice', ['rice'], 'Caprice gold parboiled rice.'),
  dry('special-rice-party', 'Party Special Rice', 'rice-grains', 'long-grain', 'Lagos, Nigeria', 1460, 'Royal Farms', ['rice', 'party'], 'Long grain selected for large pots of jollof.'),
  dry('ofada-unpolished', 'Unpolished Ofada', 'rice-grains', 'ofada', 'Ogun, Nigeria', 1950, 'Ogun Farms', ['ofada', 'unpolished'], 'Fully unpolished Ofada with bran notes.'),
  dry('abakaliki-premium', 'Premium Abakaliki Rice', 'rice-grains', 'local', 'Ebonyi, Nigeria', 1480, 'Ebonyi Mills', ['rice', 'abakaliki'], 'Hand-sorted Abakaliki rice.'),
  dry('gero-flour', 'Millet Flour (Gero)', 'rice-grains', 'millet', 'Kano, Nigeria', 1200, 'Sahel Grains', ['millet', 'flour'], 'Milled pearl millet for tuwo and kunu.', PRODUCT_IMAGES.flour),
  dry('soy-chunks', 'Soy Chunks', 'beans-legumes', 'soybeans', 'Benue, Nigeria', 2200, 'Benue Mills', ['soy', 'chunks'], 'Textured soy protein chunks.', PRODUCT_IMAGES.beans, [1, 2, 5]),
  dry('groundnut-flour', 'Groundnut Flour', 'beans-legumes', 'groundnuts', 'Kano, Nigeria', 2800, 'Sahel Grains', ['groundnut', 'flour'], 'Roasted groundnut flour for soups.', PRODUCT_IMAGES.seed, [1, 2]),
  dry('ukwa-flour', 'Ukwa Flour', 'beans-legumes', 'ukwa', 'Imo, Nigeria', 3600, 'Eastern Harvest', ['ukwa', 'flour'], 'Milled African breadfruit.', PRODUCT_IMAGES.flour, [1, 2]),
  dry('garri-delta-yellow', 'Delta Yellow Garri', 'swallows-flours', 'garri', 'Delta, Nigeria', 980, 'Delta Foods', ['garri', 'yellow'], 'Soft yellow garri from the Delta.', PRODUCT_IMAGES.flour),
  dry('fufu-ivory', 'Ivory Coast Fufu Mix', 'swallows-flours', 'fufu', 'Ghana', 2100, 'Tropical Sun', ['fufu', 'plantain'], 'Plantain-cassava fufu mix.', PRODUCT_IMAGES.flour, [1, 2, 5]),
  dry('semolina-golden-penny', 'Golden Penny Semolina', 'swallows-flours', 'semo', 'Lagos, Nigeria', 1580, 'Golden Penny', ['semolina'], 'Golden Penny semolina bags.', PRODUCT_IMAGES.flour, [1, 2, 5, 10]),
  liquid('palm-kernel-oil', 'Palm Kernel Oil', 'oils-fats', 'palm-oil', 'Ondo, Nigeria', 2100, 'Sunshine Foods', ['palm-kernel-oil'], 'Palm kernel oil for frying.', [1, 2, 5]),
  liquid('soybean-oil', 'Soybean Oil', 'oils-fats', 'vegetable-oil', 'Lagos, Nigeria', 1500, 'Kings', ['soy-oil'], 'Refined soybean oil.', [1, 2, 5, 25]),
  dry('egusi-itoo-ground', 'Ground Itoo', 'soup-thickeners', 'melon', 'Oyo, Nigeria', 3600, 'Ibadan Foods', ['itoo', 'ground'], 'Milled itoo melon.', PRODUCT_IMAGES.seed, [1, 2]),
  spice('calabash-nutmeg-ground', 'Ground Ehuru', 'local-spices', 'Anambra, Nigeria', 11500, 'Eastern Harvest', ['ehuru', 'ground'], 'Milled African nutmeg.'),
  spice('grains-of-paradise', 'Grains of Paradise', 'local-spices', 'Edo, Nigeria', 12500, 'Edo Foods', ['alligator-pepper'], 'Alligator pepper / grains of paradise.'),
  spice('dried-scent-pepper', 'Scent Pepper Mix', 'local-spices', 'Edo, Nigeria', 8200, 'Edo Foods', ['scent-leaf', 'pepper'], 'Dried scent leaf with chilli.'),
  paste('roja-paste', 'Roja Tomato Paste', 'tomato-paste', 'Lagos, Nigeria', 2500, 'Roja', ['tomato', 'paste'], 'Roja concentrated tomato paste.'),
  paste('pepper-soup-paste', 'Pepper Soup Paste', 'pepper-mix', 'Rivers, Nigeria', 3800, 'Niger Delta Foods', ['pepper-soup'], 'Wet pepper-soup base.'),
  counted('scent-leaf-dried-bunch', 'Dried Scent Leaf Bunches', 'fresh-produce', 'leafy', 'Edo, Nigeria', 180, 'Edo Foods', ['scent-leaf'], 'Dried scent-leaf wraps.', [
    { each: 1, label: '1 pack' },
    { each: 3, label: '3 packs' },
  ]),
  counted('ugu-prewashed', 'Prewashed Ugu', 'fresh-produce', 'leafy', 'Jos, Nigeria', 500, 'Jos Farms', ['ugu'], 'Washed ugu ready for soup.', bunch),
  counted('garden-egg-leaves', 'Garden Egg Leaves', 'fresh-produce', 'leafy', 'Anambra, Nigeria', 300, 'Eastern Harvest', ['garden-egg', 'leaves'], 'Anara leaves.', bunch),
  counted('efo-tete', 'Efo Tete (Amaranth)', 'fresh-produce', 'leafy', 'Oyo, Nigeria', 280, 'Ibadan Foods', ['efo', 'tete'], 'Green amaranth bunches.', bunch),
  counted('efo-shoko', 'Efo Shoko', 'fresh-produce', 'leafy', 'Oyo, Nigeria', 300, 'Ibadan Foods', ['efo', 'shoko'], 'Lagos spinach bunches.', bunch),
  counted('coco-yam-leaves', 'Cocoyam Leaves (Ede)', 'fresh-produce', 'leafy', 'Imo, Nigeria', 350, 'Eastern Harvest', ['cocoyam', 'leaves'], 'Cocoyam leaves for soup.', bunch),
  protein('ram-offal', 'Ram Offals', 'meat-offals', 'offals', 'Sokoto, Nigeria', 3200, 'Sahel Meats', ['ram', 'offal'], 'Ram offal mix for festive soups.'),
  protein('cow-skin-kpomo-dry', 'Dry Kpomo Sheets', 'meat-offals', 'ponmo', 'Oyo, Nigeria', 2000, 'Ibadan Foods', ['ponmo', 'dry'], 'Sun-dried cow skin sheets.'),
  protein('smoked-catfish-whole', 'Whole Smoked Catfish', 'fish-seafood', 'dried-fish', 'Kebbi, Nigeria', 5600, 'Kebbi Rice', ['catfish', 'smoked'], 'Whole smoked catfish.', [1, 2], PRODUCT_IMAGES.fish),
  protein('crayfish-jumbo', 'Jumbo Crayfish', 'fish-seafood', 'shrimp', 'Akwa Ibom, Nigeria', 8800, 'Niger Delta Foods', ['crayfish'], 'Large dried crayfish.', [1, 2], PRODUCT_IMAGES.fish),
  liquid('chi-exotic', 'Chi Exotic Juice', 'drinks', 'juice', 'Lagos, Nigeria', 1350, 'Chi', ['juice'], 'Chi Exotic mixed juice.', [1], PRODUCT_IMAGES.drink),
  liquid('chivita-apple', 'Chivita Apple', 'drinks', 'juice', 'Lagos, Nigeria', 1450, 'Chivita', ['juice', 'apple'], 'Apple juice drink.', [1], PRODUCT_IMAGES.drink),
  liquid('sprite-zero', 'Sprite Zero', 'drinks', 'malt-soda', 'Lagos, Nigeria', 720, 'Coca-Cola', ['soda', 'sprite'], 'Sprite Zero.', [0.35, 0.5], PRODUCT_IMAGES.drink),
  dry('ovaltine-refill', 'Ovaltine Refill', 'drinks', 'tea-coffee', 'Lagos, Nigeria', 6300, 'Ovaltine', ['ovaltine'], 'Ovaltine refill pack.', PRODUCT_IMAGES.drink, [1, 2]),
  counted('gala-sausage', 'Gala Sausage Roll', 'breakfast-bakery', 'bread', 'Lagos, Nigeria', 250, 'UAC', ['gala'], 'Gala sausage rolls.', [
    { each: 6, label: '6 rolls' },
    { each: 12, label: '12 rolls' },
  ], PRODUCT_IMAGES.breakfast),
  dry('indomie-onion', 'Indomie Onion Chicken', 'breakfast-bakery', 'cereal', 'Lagos, Nigeria', 1400, 'Indomie', ['noodles', 'indomie'], 'Onion chicken flavour noodles by weight.', PRODUCT_IMAGES.breakfast, [1, 2, 5]),
];
