import type { SeedCategoryDef } from './types';

const IMG = {
  rice: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
  beans: 'https://images.unsplash.com/photo-1515543905813-1f7d4d5c3c3d?w=400&h=400&fit=crop',
  flour: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
  oil: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
  spice: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
  veg: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=400&fit=crop',
  tuber: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=400&fit=crop',
  plantain: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400&h=400&fit=crop',
  meat: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=400&h=400&fit=crop',
  fish: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=400&fit=crop',
  dairy: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop',
  canned: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&h=400&fit=crop',
  frozen: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=400&fit=crop',
  breakfast: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&h=400&fit=crop',
  drink: 'https://images.unsplash.com/photo-1544145945-f9042533c7e6?w=400&h=400&fit=crop',
  baking: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400&h=400&fit=crop',
  seed: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=400&h=400&fit=crop',
};

export const PRODUCT_IMAGES = IMG;

export const CATEGORY_DEFS: SeedCategoryDef[] = [
  {
    slug: 'rice-grains',
    name: 'Rice & Grains',
    imageUrl: IMG.rice,
    accentColor: '#F5E6C8',
    subs: [
      { slug: 'long-grain', name: 'Long Grain' },
      { slug: 'ofada', name: 'Ofada' },
      { slug: 'local', name: 'Local' },
      { slug: 'basmati', name: 'Basmati' },
      { slug: 'jasmine', name: 'Jasmine' },
      { slug: 'parboiled', name: 'Parboiled' },
      { slug: 'millet', name: 'Millet' },
      { slug: 'sorghum', name: 'Sorghum' },
      { slug: 'acha', name: 'Acha' },
      { slug: 'maize', name: 'Maize' },
    ],
  },
  {
    slug: 'beans-legumes',
    name: 'Beans & Legumes',
    imageUrl: IMG.beans,
    accentColor: '#E8D5C4',
    subs: [
      { slug: 'oloyin', name: 'Oloyin' },
      { slug: 'brown-beans', name: 'Brown Beans' },
      { slug: 'white-beans', name: 'White Beans' },
      { slug: 'black-eyed', name: 'Black-eyed Peas' },
      { slug: 'soybeans', name: 'Soybeans' },
      { slug: 'groundnuts', name: 'Groundnuts' },
      { slug: 'ukwa', name: 'Ukwa' },
      { slug: 'lentils', name: 'Lentils' },
    ],
  },
  {
    slug: 'swallows-flours',
    name: 'Swallows & Flours',
    imageUrl: IMG.flour,
    accentColor: '#F0E4C8',
    subs: [
      { slug: 'garri', name: 'Garri' },
      { slug: 'fufu', name: 'Fufu' },
      { slug: 'semo', name: 'Semo & Semolina' },
      { slug: 'poundo', name: 'Poundo' },
      { slug: 'elubo', name: 'Elubo / Yam Flour' },
      { slug: 'cassava-flour', name: 'Cassava Flour' },
      { slug: 'plantain-flour', name: 'Plantain Flour' },
      { slug: 'okpa', name: 'Okpa' },
      { slug: 'starch', name: 'Starch' },
      { slug: 'ogi', name: 'Ogi / Pap / Custard' },
    ],
  },
  {
    slug: 'oils-fats',
    name: 'Oils & Fats',
    imageUrl: IMG.oil,
    accentColor: '#F5DCC8',
    subs: [
      { slug: 'palm-oil', name: 'Palm Oil' },
      { slug: 'vegetable-oil', name: 'Vegetable Oil' },
      { slug: 'groundnut-oil', name: 'Groundnut Oil' },
      { slug: 'coconut-oil', name: 'Coconut Oil' },
      { slug: 'shea', name: 'Shea Butter' },
      { slug: 'margarine', name: 'Margarine & Butter' },
    ],
  },
  {
    slug: 'soup-thickeners',
    name: 'Soup Thickeners & Seeds',
    imageUrl: IMG.seed,
    accentColor: '#E6D4B8',
    subs: [
      { slug: 'egusi', name: 'Egusi' },
      { slug: 'ogbono', name: 'Ogbono' },
      { slug: 'achi', name: 'Achi' },
      { slug: 'ofor', name: 'Ofor' },
      { slug: 'uziza-seed', name: 'Uziza Seed' },
      { slug: 'melon', name: 'Melon' },
    ],
  },
  {
    slug: 'spices-seasonings',
    name: 'Spices & Seasonings',
    imageUrl: IMG.spice,
    accentColor: '#D4E8D4',
    subs: [
      { slug: 'stock-cubes', name: 'Stock Cubes' },
      { slug: 'curry-thyme', name: 'Curry & Thyme' },
      { slug: 'ginger-garlic', name: 'Ginger & Garlic' },
      { slug: 'pepper-dry', name: 'Dry Pepper' },
      { slug: 'local-spices', name: 'Local Spices' },
      { slug: 'crayfish', name: 'Crayfish' },
      { slug: 'salt', name: 'Salt' },
    ],
  },
  {
    slug: 'condiments-pastes',
    name: 'Condiments & Pastes',
    imageUrl: IMG.canned,
    accentColor: '#F0C8C8',
    subs: [
      { slug: 'tomato-paste', name: 'Tomato Paste' },
      { slug: 'pepper-mix', name: 'Pepper Mix' },
      { slug: 'iru-ogiri', name: 'Iru / Ogiri' },
      { slug: 'sauces', name: 'Sauces & Vinegar' },
    ],
  },
  {
    slug: 'fresh-produce',
    name: 'Fresh Produce',
    imageUrl: IMG.veg,
    accentColor: '#C8E8C8',
    subs: [
      { slug: 'tomato', name: 'Tomato' },
      { slug: 'pepper-fresh', name: 'Fresh Pepper' },
      { slug: 'onion', name: 'Onion' },
      { slug: 'leafy', name: 'Leafy Greens' },
      { slug: 'okra', name: 'Okra' },
      { slug: 'garden-egg', name: 'Garden Egg' },
    ],
  },
  {
    slug: 'tubers-roots',
    name: 'Tubers & Roots',
    imageUrl: IMG.tuber,
    accentColor: '#E8D4B0',
    subs: [
      { slug: 'yam', name: 'Yam' },
      { slug: 'sweet-potato', name: 'Sweet Potato' },
      { slug: 'irish-potato', name: 'Irish Potato' },
      { slug: 'cassava', name: 'Cassava' },
      { slug: 'cocoyam', name: 'Cocoyam' },
    ],
  },
  {
    slug: 'plantain-banana',
    name: 'Plantain & Banana',
    imageUrl: IMG.plantain,
    accentColor: '#F5E8A0',
    subs: [
      { slug: 'unripe-plantain', name: 'Unripe Plantain' },
      { slug: 'ripe-plantain', name: 'Ripe Plantain' },
      { slug: 'banana', name: 'Banana' },
    ],
  },
  {
    slug: 'meat-offals',
    name: 'Meat & Offals',
    imageUrl: IMG.meat,
    accentColor: '#F5D0D0',
    subs: [
      { slug: 'beef', name: 'Beef' },
      { slug: 'goat', name: 'Goat' },
      { slug: 'chicken', name: 'Chicken' },
      { slug: 'turkey', name: 'Turkey' },
      { slug: 'ponmo', name: 'Ponmo' },
      { slug: 'offals', name: 'Offals' },
    ],
  },
  {
    slug: 'fish-seafood',
    name: 'Fish & Seafood',
    imageUrl: IMG.fish,
    accentColor: '#C8D8F0',
    subs: [
      { slug: 'fresh-fish', name: 'Fresh / Frozen Fish' },
      { slug: 'dried-fish', name: 'Dried Fish' },
      { slug: 'stockfish', name: 'Stockfish' },
      { slug: 'shrimp', name: 'Shrimp & Prawn' },
      { slug: 'snail', name: 'Snail' },
    ],
  },
  {
    slug: 'eggs-dairy',
    name: 'Eggs & Dairy',
    imageUrl: IMG.dairy,
    accentColor: '#FFF5D0',
    subs: [
      { slug: 'eggs', name: 'Eggs' },
      { slug: 'milk', name: 'Milk' },
      { slug: 'yoghurt', name: 'Yoghurt' },
      { slug: 'cheese', name: 'Cheese' },
    ],
  },
  {
    slug: 'canned-bottled',
    name: 'Canned & Bottled',
    imageUrl: IMG.canned,
    accentColor: '#E0E0E0',
    subs: [
      { slug: 'canned-fish', name: 'Canned Fish' },
      { slug: 'canned-tomato', name: 'Canned Tomato' },
      { slug: 'corned-beef', name: 'Corned Beef' },
      { slug: 'baked-beans', name: 'Baked Beans' },
    ],
  },
  {
    slug: 'frozen',
    name: 'Frozen',
    imageUrl: IMG.frozen,
    accentColor: '#D0E8F5',
    subs: [
      { slug: 'frozen-fish', name: 'Frozen Fish' },
      { slug: 'frozen-veg', name: 'Frozen Vegetables' },
      { slug: 'frozen-protein', name: 'Frozen Protein' },
    ],
  },
  {
    slug: 'breakfast-bakery',
    name: 'Breakfast & Bakery',
    imageUrl: IMG.breakfast,
    accentColor: '#F5E0C8',
    subs: [
      { slug: 'bread', name: 'Bread' },
      { slug: 'cereal', name: 'Cereal' },
      { slug: 'oats', name: 'Oats' },
    ],
  },
  {
    slug: 'drinks',
    name: 'Drinks',
    imageUrl: IMG.drink,
    accentColor: '#E0D4F0',
    subs: [
      { slug: 'water', name: 'Water' },
      { slug: 'malt-soda', name: 'Malt & Soft Drinks' },
      { slug: 'juice', name: 'Juice' },
      { slug: 'tea-coffee', name: 'Tea, Coffee & Cocoa' },
    ],
  },
  {
    slug: 'baking-staples',
    name: 'Baking Staples',
    imageUrl: IMG.baking,
    accentColor: '#F0E8DC',
    subs: [
      { slug: 'sugar', name: 'Sugar' },
      { slug: 'flour-wheat', name: 'Wheat Flour' },
      { slug: 'yeast', name: 'Yeast' },
      { slug: 'baking-aids', name: 'Baking Aids' },
    ],
  },
];
